huynhsontung/Screenbox

Screenbox/App.xaml.cs
Screenbox/Core/Messages/SettingsChangedMessage.cs
Screenbox/Core/SettingsOptions.cs
Screenbox/Pages/SettingsPage.xaml
Screenbox/Screenbox.csproj
Screenbox/Services/Interfaces/ISettingsService.cs
Screenbox/Services/SettingsService.cs
Screenbox/ViewModels/PlayerElementViewModel.cs
Screenbox/ViewModels/PlayerPageViewModel.cs
Screenbox/ViewModels/SettingsPageViewModel.cs

Create settings page and settings service to manage settings

Add Settings page

---

Screenbox/Controls/VolumeControl.xaml
Screenbox/Controls/VolumeControl.xaml.cs
Screenbox/Pages/SettingsPage.xaml
Screenbox/Services/Interfaces/ISettingsService.cs
Screenbox/Services/SettingsService.cs
Screenbox/ViewModels/SettingsPageViewModel.cs
Screenbox/ViewModels/VolumeViewModel.cs

Allow maximum volume to go above 100%

Volume boost feature

---

Screenbox/App.xaml.cs
Screenbox/Pages/AllVideosPage.xaml
Screenbox/Pages/AllVideosPage.xaml.cs
Screenbox/Pages/FolderViewWithHeaderPage.xaml
Screenbox/Pages/FolderViewWithHeaderPage.xaml.cs
Screenbox/Pages/SettingsPage.xaml
Screenbox/Pages/VideosPage.xaml
Screenbox/Pages/VideosPage.xaml.cs
Screenbox/Screenbox.csproj
Screenbox/Services/Interfaces/ISettingsService.cs
Screenbox/Services/SettingsService.cs
Screenbox/Strings/en-US/Resources.generated.cs
Screenbox/Strings/en-US/Resources.resw
Screenbox/ViewModels/AllVideosPageViewModel.cs
Screenbox/ViewModels/FolderViewPageViewModel.cs
Screenbox/ViewModels/FolderViewWithHeaderPageViewModel.cs
Screenbox/ViewModels/SettingsPageViewModel.cs
Screenbox/ViewModels/VideosPageViewModel.cs

- Videos library page to use the new library service in #21 
- Switch between folder view and all videos view without changing the settings

Videos library page restucture

---

Background/Background.csproj
Background/Properties/AssemblyInfo.cs
Background/UpdateTask.cs
Screenbox.sln
Screenbox/Package.appxmanifest
Screenbox/Screenbox.csproj
Screenbox/packages.lock.json

This PR adds a background task to copy lua from the installed package to `LocalState/vlc/lua` on app update.
See [libvlc-nuget/issues/13](https://code.videolan.org/videolan/libvlc-nuget/-/issues/13) for more details.

feat: Add support for lua

---

Screenbox.Core/ViewModels/PlayerPageViewModel.cs
Screenbox.Core/ViewModels/SeekBarViewModel.cs
Screenbox/Controls/SeekBar.xaml.cs
Screenbox/Pages/PlayerPage.xaml.cs

- Don't hide controls when pointer over SeekBar
- Fix SeekBar can seek to position longer than duration

fix: SeekBar bug fixes and improvements

---

Screenbox.Core/ViewModels/PlaylistViewModel.cs
Screenbox/Controls/PlaylistView.xaml.cs
Screenbox/Pages/PlayerPage.xaml
Screenbox/Pages/PlayerPage.xaml.cs

- Clearer drag & drop handling in playlist view
- Delay open playlist view flyout when drag files over play queue button

fix: playlist interaction improvements

---

Screenbox.Core/Factories/AlbumViewModelFactory.cs
Screenbox.Core/Factories/ArtistViewModelFactory.cs
Screenbox.Core/Helpers/GroupedCollectionExtensions.cs
Screenbox.Core/Helpers/MediaGroupingHelpers.cs
Screenbox.Core/Screenbox.Core.csproj
Screenbox.Core/Services/ILibraryService.cs
Screenbox.Core/Services/LibraryService.cs
Screenbox.Core/Services/SearchService.cs
Screenbox.Core/ViewModels/AlbumsPageViewModel.cs
Screenbox.Core/ViewModels/AllVideosPageViewModel.cs
Screenbox.Core/ViewModels/ArtistsPageViewModel.cs
Screenbox.Core/ViewModels/HomePageViewModel.cs
Screenbox.Core/ViewModels/MusicPageViewModel.cs
Screenbox.Core/ViewModels/SettingsPageViewModel.cs
Screenbox.Core/ViewModels/SongsPageViewModel.cs
Screenbox.Core/ViewModels/VideosPageViewModel.cs
Screenbox/Pages/AllVideosPage.xaml
Screenbox/Pages/AllVideosPage.xaml.cs
Screenbox/Pages/MusicPage.xaml
Screenbox/Pages/MusicPage.xaml.cs
Screenbox/Pages/VideosPage.xaml.cs

- Rework LibararyService to use event-based updates instead of a long-running task
- Poll the LibraryService if fetching takes too long
- Libray fetching in HomePageViewModel should only run once

feat: streaming media library to UI

---

Screenbox.Core/Enums/ResourceName.cs
Screenbox.Core/Messages/SubtitleAddedNotificationMessage.cs
Screenbox.Core/Screenbox.Core.csproj
Screenbox.Core/ViewModels/AudioTrackSubtitleViewModel.cs
Screenbox.Core/ViewModels/NotificationViewModel.cs
Screenbox.Core/ViewModels/PlayerInteractionViewModel.cs
Screenbox/Strings/en-US/Resources.generated.cs
Screenbox/Strings/en-US/Resources.resw

feat: show success notification when adding subtitle file

---

Screenbox.Core/ViewModels/PlayerInteractionViewModel.cs
Screenbox/Controls/PlayerElement.xaml

Use `<` and `>` key for toggling playback speed.

feat: add playback speed toggle shortcut

---

.config/dotnet-tools.json
.github/workflows/main.yml
Screenbox/Controls/Templates/ArtistGridViewItem.xaml
Screenbox/Controls/Templates/VideoGridViewItem.xaml
scripts/lint-xaml.ps1

Add XAML lint job using [XamlStyler.Console](https://github.com/Xavalon/XamlStyler/wiki/Script-Integration)

ci: add XAML lint job

---

Screenbox.Core/ViewModels/MainPageViewModel.cs
Screenbox/Controls/CustomNavigationView.cs
Screenbox/Pages/MainPage.xaml
Screenbox/Pages/MainPage.xaml.cs
Screenbox/Pages/PlayerPage.xaml
Screenbox/Pages/PlayerPage.xaml.cs

Use `GamepadY` to restore player instead of `GamepadView`

fix: adjust gamepad handling

---

Screenbox/Pages/MusicPage.xaml
Screenbox/Pages/VideosPage.xaml

Override the NavigationView default margins

fix: Remove NavigationView top nav margin

---

Screenbox.Core/ViewModels/SeekBarViewModel.cs

WCT bug: https://github.com/CommunityToolkit/WindowsCommunityToolkit/issues/4905

fix: wrong offset position offset when seeking using hotkeys

---

Screenbox.sln
Screenbox/MultilingualResources/Screenbox.zh-Hans.xlf
Screenbox/Screenbox.csproj
Screenbox/Strings/zh-Hans/ManifestResources.resw
Screenbox/Strings/zh-Hans/Resources.resw

Hi, following the translation method you mentioned, I have successfully added Chinese support to this software. I have tested it on my computer and also had friends help with testing to ensure there are no issues.
However, I'm not very familiar with UWP software development, so currently, it seems like the software's language is changing according to the user's computer system settings. Perhaps I should add an option to change the language in the software settings, but I'm not sure how to do that 😂.
This is a screenshot of the effect comparison

Add Chinese translation.

---

Screenbox.Core/ViewModels/MediaViewModel.cs
Screenbox/Pages/PlayerPage.xaml

feat: file name as subtitle for video file

---

Screenbox/Pages/SettingsPage.xaml

Improved library folder appearance in settings and added display name

---

Screenbox.Core/Services/FilesService.cs
Screenbox.Core/Services/LibraryService.cs
Screenbox.Core/ViewModels/AllVideosPageViewModel.cs
Screenbox.Core/ViewModels/SongsPageViewModel.cs

Remove soft file fetch cap of 5000

fix: incomplete fetch media list from libraries

---

Screenbox/App.xaml.cs

https://learn.microsoft.com/en-us/windows/uwp/xbox-apps/turn-off-overscan

fix: disable overscan on xbox

---

README.md
Screenbox/Strings/en-US/STORE.md
crowdin.yml

chore: update doc

---

Screenbox.Core/Playback/PlaybackSubtitleTrackList.cs
Screenbox.Core/Playback/VlcMediaPlayer.cs
Screenbox.Core/ViewModels/AudioTrackSubtitleViewModel.cs
Screenbox.Core/ViewModels/PlayerControlsViewModel.cs
Screenbox/Controls/AudioTrackSubtitlePicker.xaml
Screenbox/Controls/AudioTrackSubtitlePicker.xaml.cs
Screenbox/Controls/PlayerControls.xaml
Screenbox/Controls/PlayerControls.xaml.cs
Screenbox/Controls/Styles/CustomFlyoutPresenter.xaml
Screenbox/Screenbox.csproj
Screenbox/Strings/ar-SA/Resources.resw
Screenbox/Strings/en-US/Resources.generated.cs
Screenbox/Strings/en-US/Resources.resw
Screenbox/Strings/es-ES/Resources.resw
Screenbox/Strings/ro-RO/Resources.resw
Screenbox/Strings/ru-RU/Resources.resw
Screenbox/Strings/zh-Hans/Resources.resw

feat: subtitle timing offset options

---

Screenbox.Core/ViewModels/PlayerControlsViewModel.cs
Screenbox.Core/ViewModels/SettingsPageViewModel.cs
Screenbox/Commands/SetPlaybackOptionsCommand.cs
Screenbox/Controls/PlayerControls.xaml
Screenbox/Controls/SetOptionsDialog.xaml
Screenbox/Controls/SetOptionsDialog.xaml.cs
Screenbox/Pages/SettingsPage.xaml
Screenbox/Pages/SettingsPage.xaml.cs

Add the ability to set playback options on the active media.
Reworked set arguments UI in Settings

feat: improve set playback options experience

---

Screenbox.Core/Services/FilesService.cs
Screenbox/Package.appxmanifest

feat: add opus file support

---

Screenbox.Core/Helpers/FilesHelpers.cs
Screenbox.Core/Screenbox.Core.csproj
Screenbox.Core/Services/FilesService.cs
Screenbox.Core/Services/SystemMediaTransportControlsService.cs
Screenbox.Core/ViewModels/MediaViewModel.cs
Screenbox.Core/ViewModels/PlayerPageViewModel.cs
Screenbox/Converters/MediaGlyphConverter.cs
Screenbox/Pages/PlayerPage.xaml.cs

Mentioned in #97 
Use file extension to detect media type instead of using ContentType string

fix: incorrect media type detection

---

Screenbox/Controls/PlayerElement.xaml

fix: white line at the bottom of video surface

---

Screenbox/App.xaml
Screenbox/Pages/AlbumDetailsPage.xaml
Screenbox/Pages/AlbumsPage.xaml
Screenbox/Pages/AllVideosPage.xaml
Screenbox/Pages/ArtistDetailsPage.xaml
Screenbox/Pages/ArtistsPage.xaml
Screenbox/Pages/FolderListViewPage.xaml
Screenbox/Pages/FolderViewPage.xaml
Screenbox/Pages/HomePage.xaml
Screenbox/Pages/MainPage.xaml
Screenbox/Pages/MusicPage.xaml
Screenbox/Pages/NetworkPage.xaml
Screenbox/Pages/PlayQueuePage.xaml
Screenbox/Pages/PlayerPage.xaml
Screenbox/Pages/Search/AlbumSearchResultPage.xaml
Screenbox/Pages/Search/ArtistSearchResultPage.xaml
Screenbox/Pages/Search/SearchResultPage.xaml
Screenbox/Pages/Search/SongSearchResultPage.xaml
Screenbox/Pages/Search/VideoSearchResultPage.xaml
Screenbox/Pages/SettingsPage.xaml
Screenbox/Pages/SongsPage.xaml
Screenbox/Pages/VideosPage.xaml

Some improvements to navigation and xaml consistency, here some of the changes:
- xml namespaces
- left side gutter is no longer a deadspace
- some buttons were missing accessibility tags
- converted some {x:Bind}
- better App.xaml readability

fix: better content navigation and minor a11y improvements

---

Screenbox/App.xaml
Screenbox/Controls/Interactions/AutoFocusBehavior.cs
Screenbox/Pages/AlbumDetailsPage.xaml
Screenbox/Pages/AlbumsPage.xaml
Screenbox/Pages/AllVideosPage.xaml
Screenbox/Pages/ArtistDetailsPage.xaml
Screenbox/Pages/ArtistsPage.xaml
Screenbox/Pages/FolderListViewPage.xaml
Screenbox/Pages/FolderViewPage.xaml
Screenbox/Pages/HomePage.xaml
Screenbox/Pages/MusicPage.xaml
Screenbox/Pages/PlayQueuePage.xaml
Screenbox/Pages/SongsPage.xaml
Screenbox/Pages/VideosPage.xaml
Screenbox/Screenbox.csproj

Fixes #192 
Create a custom `AutoFocusBehavior` that better handles auto focus on keyboard/gamepad navigation.

fix: auto focus double triggering

---

Screenbox/App.xaml
Screenbox/Controls/Interactions/ListViewContextTriggerBehavior.cs
Screenbox/Controls/Interactions/MediaListViewItemBehavior.cs
Screenbox/Controls/Templates/AlbumGridViewItem.xaml
Screenbox/Controls/Templates/ArtistGridViewItem.xaml
Screenbox/Pages/AlbumsPage.xaml
Screenbox/Pages/ArtistsPage.xaml
Screenbox/Pages/Search/AlbumSearchResultPage.xaml
Screenbox/Pages/Search/ArtistSearchResultPage.xaml
Screenbox/Pages/Search/SearchResultPage.xaml
Screenbox/Strings/en-US/Resources.generated.cs
Screenbox/Strings/en-US/Resources.resw

feat: menu flyout for albums and artists

---

Screenbox.Core/Services/FilesService.cs
Screenbox.Core/Services/IFilesService.cs
Screenbox.Core/Services/ISettingsService.cs
Screenbox.Core/Services/LibraryService.cs
Screenbox.Core/Services/SettingsService.cs
Screenbox.Core/ViewModels/SettingsPageViewModel.cs
Screenbox/Pages/SettingsPage.xaml
Screenbox/Strings/en-US/Resources.generated.cs
Screenbox/Strings/en-US/Resources.resw

feat: add option to disable indexer

---

Screenbox.Core/Helpers/FilesHelpers.cs
Screenbox.Core/Services/FilesService.cs
Screenbox/Package.appxmanifest

Allow all file extensions to be open from the open file picker.

feat: add support for .m2ts extensions

---

Screenbox/Screenbox.csproj
Screenbox/Strings/it-IT/Resources.resw
Screenbox/Strings/nl-NL/ManifestResources.resw
Screenbox/Strings/nl-NL/Resources.resw
Screenbox/Strings/nl-NL/STORE.md
Screenbox/Strings/pl-PL/ManifestResources.resw
Screenbox/Strings/pl-PL/Resources.resw
Screenbox/Strings/pl-PL/STORE.md
Screenbox/Strings/ro-RO/Resources.resw

Add support for Polish and Dutch

l10n: Crowdin updates

---

Screenbox.Core/ViewModels/PlayerPageViewModel.cs
Screenbox/Pages/PlayerPage.xaml

Home key jumps to the beginning.
End key jumps to the end.

feat: add Home and End keys for quick seek

---

Screenbox/Pages/SettingsPage.xaml
Screenbox/Strings/en-US/Resources.generated.cs
Screenbox/Strings/en-US/Resources.resw

Mentioned in https://github.com/huynhsontung/Screenbox/issues/249#issuecomment-1858454359

l10n: localize "Set arguments" text

---

Screenbox.Core/Helpers/FilesHelpers.cs
Screenbox.Core/ViewModels/AudioTrackSubtitleViewModel.cs
Screenbox.Core/ViewModels/PlayerPageViewModel.cs

Also refactor subtitle list usage.
Resolves #222

feat: add support for VTT subtitle

---

Screenbox.Core/Factories/AlbumViewModelFactory.cs
Screenbox.Core/Factories/ArtistViewModelFactory.cs
Screenbox.Core/Models/MediaInfo.cs
Screenbox.Core/Screenbox.Core.csproj
Screenbox.Core/ViewModels/AlbumDetailsPageViewModel.cs
Screenbox.Core/ViewModels/AlbumViewModel.cs
Screenbox.Core/ViewModels/ArtistDetailsPageViewModel.cs
Screenbox.Core/ViewModels/ArtistViewModel.cs
Screenbox.Core/ViewModels/FileMediaViewModel.cs
Screenbox.Core/ViewModels/MediaViewModel.cs
Screenbox.Core/ViewModels/PropertyViewModel.cs
Screenbox/Controls/MediaListViewItem.xaml

Track media properties from `Windows.Storage.FileProperties` in our own `MediaInfo` structure.

refactor: consolidate media properties into MediaInfo

---

Screenbox.Core/Services/ISettingsService.cs
Screenbox.Core/Services/LibraryService.cs
Screenbox.Core/Services/SettingsService.cs
Screenbox.Core/ViewModels/FolderViewPageViewModel.cs
Screenbox.Core/ViewModels/SettingsPageViewModel.cs
Screenbox.Core/ViewModels/VideosPageViewModel.cs
Screenbox/Package.appxmanifest
Screenbox/Pages/SettingsPage.xaml
Screenbox/Pages/SettingsPage.xaml.cs
Screenbox/Strings/en-US/Resources.generated.cs
Screenbox/Strings/en-US/Resources.resw

feat: scan external storage devices to include in library on Xbox

---

Screenbox/App.xaml.cs

Read [Reveal Focus](https://learn.microsoft.com/en-us/windows/apps/design/style/reveal-focus)

feat: use reveal focus visual on Xbox

---

.github/workflows/main.yml
Screenbox.Core/Screenbox.Core.csproj
Screenbox.Core/packages.lock.json
Screenbox/Screenbox.csproj
Screenbox/packages.lock.json

New LibVLC is built by ucrt container using llvm17 allows ARM64 support
https://github.com/huynhsontung/libvlc-nuget/pull/7
Related: #179

feat: ARM64 support

---

Screenbox.Core/Services/LibraryService.cs

fix: media glyph may show up as globe icon randomly

---

Screenbox/Strings/id-ID/ManifestResources.resw
Screenbox/Strings/id-ID/Resources.resw
Screenbox/Strings/id-ID/STORE.md

This PR adds Indonesian translation to the app

l10n: Add Indonesian translation

---

Screenbox/Pages/PlayerPage.xaml
Screenbox/Pages/PlayerPage.xaml.cs

Simple translate animation to make the album art background more dynamic.
https://github.com/huynhsontung/Screenbox/assets/31434093/50d64fc0-f2bb-4aaa-ad94-d783a3d04692

feat: add animation for the album art background

---

Screenbox/Pages/MainPage.xaml

feat: add acrylic material to NavigationView side pane

---

Screenbox.Core/Factories/MediaViewModelFactory.cs
Screenbox.Core/ViewModels/MediaListViewModel.cs
Screenbox.Core/ViewModels/MediaViewModel.cs

Handle IOException when dealing with file path URI.

fix: app crash by loading media details

---

Screenbox.Core/ViewModels/AlbumsPageViewModel.cs
Screenbox.Core/ViewModels/AudioTrackSubtitleViewModel.cs
Screenbox.Core/ViewModels/MediaViewModel.cs
Screenbox/App.xaml
Screenbox/Controls/Interactions/ThumbnailGridViewBehavior.cs
Screenbox/Converters/FirstOrDefaultConverter.cs
Screenbox/Pages/AlbumDetailsPage.xaml
Screenbox/Pages/AlbumDetailsPage.xaml.cs
Screenbox/Pages/ArtistDetailsPage.xaml
Screenbox/Screenbox.csproj

Also handle an exception when auto-load subtitles for a video.

fix: album art binding and loading exceptions

---

Screenbox/Controls/CommonGridViewItem.xaml

fix: play album command not updating correctly in a GridView

---

Screenbox.Core/Services/LibraryService.cs
Screenbox.Core/ViewModels/HomePageViewModel.cs
Screenbox.Core/ViewModels/SettingsPageViewModel.cs

fix: handle library fetch exceptions at view model level where possible

---

Screenbox.Core/ViewModels/PropertyViewModel.cs

Related [link](https://learn.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/m/multiplication-sign)
Thanks to @Jay-o-Way and @0x5bfa

chore: replace resolution separator character

---

.github/workflows/main.yml
PRIVACY.md
Screenbox.Core/Screenbox.Core.csproj
Screenbox.Core/Services/LogService.cs
Screenbox.Core/packages.lock.json
Screenbox/App.xaml.cs
Screenbox/Screenbox.csproj
Screenbox/Secrets.cs.template
Screenbox/packages.lock.json

Visual Studio App Center is sunsetting so we need a replacement for error tracking.

feat: use Sentry for error collection

---

Screenbox.Core/Helpers/CollectionExtensions.cs
Screenbox.Core/Helpers/ListGrouping.cs
Screenbox.Core/Helpers/MediaGroupingHelpers.cs
Screenbox.Core/Screenbox.Core.csproj
Screenbox.Core/ViewModels/AlbumsPageViewModel.cs
Screenbox.Core/ViewModels/ArtistsPageViewModel.cs
Screenbox.Core/ViewModels/BaseMusicContentViewModel.cs
Screenbox.Core/ViewModels/CommonViewModel.cs
Screenbox.Core/ViewModels/MusicPageViewModel.cs
Screenbox.Core/ViewModels/SongsPageViewModel.cs
Screenbox/App.xaml
Screenbox/Controls/Interactions/GroupingOverviewBehavior.cs
Screenbox/Pages/AlbumsPage.xaml
Screenbox/Pages/AlbumsPage.xaml.cs
Screenbox/Pages/ArtistsPage.xaml
Screenbox/Pages/ArtistsPage.xaml.cs
Screenbox/Pages/FolderListViewPage.xaml.cs
Screenbox/Pages/FolderViewPage.xaml.cs
Screenbox/Pages/MusicPage.xaml
Screenbox/Pages/NetworkPage.xaml.cs
Screenbox/Pages/SongsPage.xaml
Screenbox/Pages/SongsPage.xaml.cs
Screenbox/Screenbox.csproj
Screenbox/Strings/en-US/Resources.generated.cs
Screenbox/Strings/en-US/Resources.resw

Add options to sort the music pages. Sort options for each page:
- Songs: title, album, artist, released year
- Albums: title, artist, released year
- Aritsts: N/A
Closes #370

feat: add sort options for music pages

---

Screenbox.Core/Factories/AlbumViewModelFactory.cs
Screenbox.Core/Helpers/ListGrouping.cs
Screenbox.Core/Models/PersistentSongRecord.cs
Screenbox.Core/Models/PersistentVideoRecord.cs
Screenbox.Core/Services/FilesService.cs
Screenbox.Core/Services/LibraryService.cs
Screenbox.Core/ViewModels/AlbumViewModel.cs
Screenbox.Core/ViewModels/AlbumsPageViewModel.cs
Screenbox.Core/ViewModels/MediaViewModel.cs
Screenbox.Core/ViewModels/SongsPageViewModel.cs
Screenbox/Pages/AlbumsPage.xaml
Screenbox/Pages/SongsPage.xaml
Screenbox/Strings/en-US/Resources.generated.cs
Screenbox/Strings/en-US/Resources.resw

Track the date a song or an album was added to the library and let the user sort using it.

feat: track media date added to the library

---

Screenbox.Core/Playback/PlaybackSubtitleTrackList.cs
Screenbox.Core/Playback/VlcMediaPlayer.cs

Should fix a problem mentioned in #387

fix: spu not pre-select correctly

---

Screenbox/Controls/PlaylistView.xaml

fix: text clipping with playlist flyout in some languages

---

Screenbox.Core/ViewModels/LivelyWallpaperPlayerViewModel.cs
Screenbox.Core/ViewModels/LivelyWallpaperSelectorViewModel.cs
Screenbox/Controls/LivelyWebWallpaperPlayer.xaml.cs
Screenbox/Pages/PlayerPage.xaml

- Lively selector flyout overflowing
- Visual change not taking effect

fix: various Lively related issues

---

Screenbox.Core/Helpers/FilesHelpers.cs
Screenbox/Package.appxmanifest

feat: add associations for RealMedia and ASF file types

---

Screenbox/Controls/AcceleratorService.cs
Screenbox/Controls/LivelyWebWallpaperPlayer.xaml.cs
Screenbox/Controls/PlayerControls.xaml
Screenbox/Controls/PlayerElement.xaml

Enforce LTR and RTL flow in specific UI elements. Fixes #429

fix: unintended UI flipping in RTL languages

---

Screenbox.Core/ViewModels/PlaylistViewModel.cs
Screenbox/Controls/PlaylistView.xaml
Screenbox/Controls/PlaylistView.xaml.cs

- Fixed play next not working
- Fixed moving up or moving down items refreshes the whole list
https://github.com/user-attachments/assets/d1a35f0d-2ae6-4982-b0db-4decd150e0c4

fix: various PlaylistView issues

---

Screenbox.Core/ViewModels/AlbumDetailsPageViewModel.cs
Screenbox.Core/ViewModels/AllVideosPageViewModel.cs
Screenbox.Core/ViewModels/ArtistDetailsPageViewModel.cs
Screenbox.Core/ViewModels/CommonViewModel.cs
Screenbox.Core/ViewModels/HomePageViewModel.cs
Screenbox.Core/ViewModels/SongsPageViewModel.cs
Screenbox/App.xaml
Screenbox/Controls/CommonGridViewItem.xaml
Screenbox/Controls/PlaylistView.xaml
Screenbox/Controls/SeekBar.xaml
Screenbox/Pages/AlbumDetailsPage.xaml
Screenbox/Pages/AllVideosPage.xaml
Screenbox/Pages/ArtistDetailsPage.xaml
Screenbox/Pages/HomePage.xaml
Screenbox/Pages/PlayerPage.xaml
Screenbox/Pages/Search/SearchResultPage.xaml
Screenbox/Pages/Search/SongSearchResultPage.xaml
Screenbox/Pages/Search/SongSearchResultPage.xaml.cs
Screenbox/Pages/SettingsPage.xaml
Screenbox/Pages/SongsPage.xaml
Screenbox/Strings/en-US/Resources.generated.cs
Screenbox/Strings/en-US/Resources.resw

- Make media context menu available in more places, such as Songs, Album details, Artist details, and Search result pages.
- Add commands to show album or artist in the context menu.

feat: improve media context menu

---

Screenbox/Controls/Interactions/NavigationViewKeyboardBehavior.cs
Screenbox/Pages/MainPage.xaml

Move style changes from the NavigationView keyboard behavior to the page resources

style: add animated icon to navigation view search button

---

Screenbox/App.xaml
Screenbox/Controls/MediaListViewItem.xaml
Screenbox/Controls/PlayerControls.xaml
Screenbox/Converters/ThicknessFilterConverter.cs
Screenbox/Styles/Button.xaml

- Adds every filter combination
- Renames the converter keys to align with the corner radius converter in WinUI
- Standardizes the toolkit converter namespace

chore: minor improvement to thickness converter

---

Screenbox/Pages/SettingsPage.xaml
Screenbox/Styles/CommandBar.xaml

Some slight adjustments to improve high contrast and focus visual.

style: minor UI improvements

---

Screenbox.Core/Playback/PlaybackVideoTrackList.cs
Screenbox.Core/Playback/VideoTrack.cs
Screenbox.Core/Playback/VlcMediaPlayer.cs
Screenbox.Core/ViewModels/CompositeTrackPickerViewModel.cs
Screenbox/Controls/CompositeTrackPicker.xaml

Adds support for video tracks. Still up to debate whether to display the video tracks list view when there is only one track.

feat: add video track selection

---

.editorconfig

Adjusts the `var preferences` and adds a implicit type diagnostic rule. Also includes some minor reordering.

chore: minor coding conventions editorconfig update

---

Screenbox.Core/Services/ISettingsService.cs
Screenbox.Core/Services/SettingsService.cs
Screenbox.Core/ViewModels/PlayerControlsViewModel.cs
Screenbox.Core/ViewModels/SettingsPageViewModel.cs
Screenbox/Controls/PlayerControls.xaml
Screenbox/Controls/TimeDisplay.xaml.cs
Screenbox/Pages/SettingsPage.xaml
Screenbox/Strings/en-US/Resources.resw

feat: add option to hide chapter name

---

Screenbox.Core/Models/Language.cs
Screenbox.Core/Screenbox.Core.csproj
Screenbox.Core/ViewModels/SettingsPageViewModel.cs
Screenbox/Converters/LanguageLayoutDirectionToFlowDirectionConverter.cs
Screenbox/Pages/SettingsPage.xaml
Screenbox/Pages/SettingsPage.xaml.cs
Screenbox/Screenbox.csproj
Screenbox/Strings/en-US/Resources.resw

feat: add option to change the app's display language

---

Screenbox/App.xaml
Screenbox/Controls/PlaylistView.xaml
Screenbox/Converters/ThicknessFiltersConverter.cs
Screenbox/Screenbox.csproj
Screenbox/Styles/Button.xaml

chore: rename thickness converter filter property

---

Screenbox/Converters/LanguageLayoutDirectionToFlowDirectionConverter.cs
Screenbox/Pages/SettingsPage.xaml

Refactored `LanguageLayoutDirectionToFlowDirectionConverter` to use function binding
- Extracts the conversion logic to a separate method
- Updates `SettingsPage.xaml` to use the static `ToFlowDirection` method directly

chore: refactor LanguageLayoutDirection converter
