huynhsontung/Screenbox

Screenbox.Core/Common/ResourceHelper.cs, Screenbox.Core/Messages/RaiseLibraryAccessDeniedNotificationMessage.cs, Screenbox.Core/Screenbox.Core.csproj, Screenbox.Core/Services/ILibraryService.cs, Screenbox.Core/Services/LibraryService.cs, Screenbox.Core/ViewModels/AlbumsPageViewModel.cs, Screenbox.Core/ViewModels/AllVideosPageViewModel.cs, Screenbox.Core/ViewModels/ArtistsPageViewModel.cs, Screenbox.Core/ViewModels/HomePageViewModel.cs, Screenbox.Core/ViewModels/MusicPageViewModel.cs, Screenbox.Core/ViewModels/NotificationViewModel.cs, Screenbox.Core/ViewModels/SettingsPageViewModel.cs, Screenbox.Core/ViewModels/SongsPageViewModel.cs, Screenbox.Core/ViewModels/VideosPageViewModel.cs, Screenbox/Pages/AlbumsPage.xaml.cs, Screenbox/Pages/ArtistsPage.xaml.cs, Screenbox/Pages/SettingsPage.xaml.cs, Screenbox/Pages/SongsPage.xaml.cs, Screenbox/Pages/VideosPage.xaml.cs, Screenbox/Strings/en-US/Resources.generated.cs, Screenbox/Strings/en-US/Resources.resw
Fixes #41 
View models were interacting with `StorageLibrary` directly without exception handling. This PR route all `StorageLibrary` access through `ILibraryService` with proper exception handling.
=> fix: Handle library access gracefully

Screenbox.Core/Playback/VlcMediaPlayer.cs
When a network location is detected, try to repeatedly parse it until the final video is resolved.
=> fix: Better network parse handling

Screenbox.Core/Messages/ShowPlayPauseBadgeMessage.cs, Screenbox.Core/ViewModels/PlayerInteractionViewModel.cs, Screenbox.Core/ViewModels/PlayerPageViewModel.cs, Screenbox/Pages/PlayerPage.xaml
Add debounce on the play pause toggle when tapping on the video surface to prevent micro plays/pauses.
=> fix: Micro plays/pauses when double tapping the video

Screenbox.Core/ViewModels/PlayerPageViewModel.cs
Player can collapse in fullscreen or compact overlay mode using the hardware back button. This breaks the layout logic.
When fullscreen mode or compact overlay mode is active, the hardware back button now exits those modes instead and only collapses the player when in default mode.
=> fix: Hardware back button breaks layout in fullscreen and compact overlay

Screenbox.Core/Messages/MediaPlayerRequestMessage.cs, Screenbox.Core/Screenbox.Core.csproj, Screenbox.Core/ViewModels/AudioTrackSubtitleViewModel.cs, Screenbox.Core/ViewModels/PlayerElementViewModel.cs, Screenbox.Core/ViewModels/PlayerInteractionViewModel.cs, Screenbox/Controls/PlayerElement.xaml, Screenbox/Controls/PlayerElement.xaml.cs, Screenbox/Controls/PlaylistView.xaml.cs, Screenbox/Pages/AlbumDetailsPage.xaml, Screenbox/Pages/AlbumsPage.xaml, Screenbox/Pages/AllVideosPage.xaml, Screenbox/Pages/ArtistDetailsPage.xaml, Screenbox/Pages/ArtistsPage.xaml, Screenbox/Pages/FolderListViewPage.xaml, Screenbox/Pages/FolderViewPage.xaml, Screenbox/Pages/HomePage.xaml, Screenbox/Pages/MainPage.xaml.cs, Screenbox/Pages/MusicPage.xaml, Screenbox/Pages/NetworkPage.xaml, Screenbox/Pages/PlayQueuePage.xaml, Screenbox/Pages/PlayerPage.xaml, Screenbox/Pages/PlayerPage.xaml.cs, Screenbox/Pages/SettingsPage.xaml, Screenbox/Pages/SongsPage.xaml, Screenbox/Pages/VideosPage.xaml
- Adaptively resize the interactable area in the player page to allow XY navigation.
- Better focus-changing behaviour when navigating with a keyboard
- Handle Window-level back navigation (Alt+Left)
- Bind some gamepad keys to common operations.
- Right thumbstick up/down for volume change
- Right thumbstick left/right for seeking
- X for play/pause toggle
- Y for audio and caption picker
=> feat: Improve Gamepad and keyboard experience

Screenbox.Core/Helpers/DisplayRequestTracker.cs, Screenbox.Core/Screenbox.Core.csproj, Screenbox.Core/ViewModels/PlayerElementViewModel.cs
Fixes #52 
The display request tracker will now be active no matter what the type of media.
=> fix: Simplify active display request tracker

Screenbox/Controls/PlayerControls.xaml
Added another keyboard shortcut to Compact Overlay, again mirroring the inbox app.
=> feat: add Compact Overlay keystroke

Screenbox.Core/ViewModels/PlayerPageViewModel.cs, Screenbox/Pages/PlayerPage.xaml, Screenbox/Pages/PlayerPage.xaml.cs
Hide controls using (B) and reveal with (A) like many other media players on Xbox.
=> fix: controls visibility with gamepad

Screenbox.Core/ViewModels/SeekBarViewModel.cs, Screenbox/Controls/CustomSlider.cs, Screenbox/Controls/SeekBar.xaml, Screenbox/Screenbox.csproj
Use custom `Slider` to disable keyboard handling when player is expanded.
=> fix: override seekbar keyboard interaction

Screenbox.Core/Common/NavigationMetadata.cs, Screenbox.Core/Screenbox.Core.csproj, Screenbox.Core/Services/INavigationService.cs, Screenbox.Core/Services/NavigationService.cs, Screenbox.Core/ViewModels/AlbumDetailsPageViewModel.cs, Screenbox.Core/ViewModels/ArtistDetailsPageViewModel.cs, Screenbox.Core/ViewModels/CommonViewModel.cs, Screenbox.Core/ViewModels/FolderListViewPageViewModel.cs, Screenbox.Core/ViewModels/FolderViewPageViewModel.cs, Screenbox.Core/ViewModels/FolderViewWithHeaderPageViewModel.cs, Screenbox.Core/ViewModels/MainPageViewModel.cs, Screenbox.Core/ViewModels/VideosPageViewModel.cs, Screenbox/Pages/AlbumDetailsPage.xaml.cs, Screenbox/Pages/ArtistDetailsPage.xaml.cs, Screenbox/Pages/FolderListViewPage.xaml.cs, Screenbox/Pages/FolderViewPage.xaml.cs, Screenbox/Pages/MainPage.xaml.cs, Screenbox/Pages/VideosPage.xaml, Screenbox/Pages/VideosPage.xaml.cs
Create `NavigationMetadata` to carry root page association across navigations.
Clicking the first item in Video Folders breadcrumb bar should go back to the Videos main page. `NavigationMetadata` allows `FolderViewWithHeaderPage` to be aware of it being navigated from `VideosPage`.
=> feat: richer navigation context

Screenbox.Core/ViewModels/SeekBarViewModel.cs
When one media ends, the rounding logic that sets seek bar value to media duration doesn't check if a new media has been loaded or not.
=> fix: media starts where last one ends

Screenbox.Core/Playback/VlcMediaPlayer.cs, Screenbox.Core/ViewModels/SeekBarViewModel.cs, Screenbox/Controls/SeekBar.xaml, Screenbox/Pages/PlayerPage.xaml.cs
Separate setter logic for UI Time value `SeekBarViewModel.Time` and the player's Position value `IMediaPlayer.Position` to avoid accidental value changes for both sides.
=> fix: seek bar value propagation logic

.github/workflows/main.yml, Screenbox/Screenbox.csproj
Stop building ARM version into the appxbundle due to PRI merging issue. String resources got messed up as a result.
Related: #123 
https://developercommunity.visualstudio.com/t/get-merge-failure-for-shared-merged-pri-file-0x800/107928
Screenshot of WACK raising error
=> ci: disable ARM bundling

Screenbox/MultilingualResources/Screenbox.zh-Hans.xlf, Screenbox/Strings/en-US/Resources.generated.cs, Screenbox/Strings/en-US/Resources.resw
Minor fix.
I think the other translation made the same mistake. Passed through a translator and see the same.
Not fluent or knowledgeable enough to attempt to fix it.
=> fix: no video subtext string change

Screenbox.Core/Playback/PlaybackChapterList.cs, Screenbox.Core/Playback/PlaybackItem.cs, Screenbox.Core/Playback/VlcMediaPlayer.cs, Screenbox.Core/ViewModels/MediaViewModel.cs, Screenbox.Core/ViewModels/SeekBarViewModel.cs, Screenbox/Controls/ChapterProgressBar.xaml
- Fixed thread conflict can occur when updating the chapter list. [Exception](https://appcenter.ms/users/highpine/apps/Screenbox/crashes/errors/2598909319u/overview). Initiate chapter list update from UI thread.
- Fixed chapter progress bar item in ChapterProgressBar sometimes has Min and Max value drift.
=> fix: chapter not updating properly

Screenbox.Core/ViewModels/PlayerPageViewModel.cs
=> fix: controls not hiding when double click to go fullscreen

Screenbox/Controls/PlayerControls.xaml, Screenbox/Converters/PlayPauseGlyphConverter.cs
According to @Jay-o-Way findings [here](https://github.com/microsoft/PowerToys/issues/10331), those deprecated glyphs ([Segoe Fluent Icons font](https://learn.microsoft.com/en-us/windows/apps/design/style/segoe-fluent-icons-font#icon-list)) cause issues with CJK languages.
Maybe affected #123.
=> chore: Update to deprecated glyphs

Screenbox.Core/Enums/ResourceName.cs, Screenbox.Core/Playback/PlaybackItem.cs, Screenbox.Core/Services/IMediaService.cs, Screenbox.Core/Services/ISettingsService.cs, Screenbox.Core/Services/MediaService.cs, Screenbox.Core/Services/SettingsService.cs, Screenbox.Core/ViewModels/CommonViewModel.cs, Screenbox.Core/ViewModels/HomePageViewModel.cs, Screenbox.Core/ViewModels/MediaViewModel.cs, Screenbox.Core/ViewModels/PlayerElementViewModel.cs, Screenbox.Core/ViewModels/SettingsPageViewModel.cs, Screenbox/Commands/SetPlaybackOptionsCommand.cs, Screenbox/Controls/PlaylistView.xaml, Screenbox/Controls/SetOptionsDialog.xaml, Screenbox/Controls/SetOptionsDialog.xaml.cs, Screenbox/MultilingualResources/Screenbox.zh-Hans.xlf, Screenbox/Pages/AllVideosPage.xaml, Screenbox/Pages/FolderListViewPage.xaml, Screenbox/Pages/FolderViewPage.xaml, Screenbox/Pages/HomePage.xaml, Screenbox/Pages/HomePage.xaml.cs, Screenbox/Pages/SettingsPage.xaml, Screenbox/Pages/SettingsPage.xaml.cs, Screenbox/Pages/SongsPage.xaml, Screenbox/Screenbox.csproj, Screenbox/Strings/en-US/Resources.generated.cs, Screenbox/Strings/en-US/Resources.resw
Closes #42
Add the ability to set VLC CLI options per media file or globally.
Setting playback options for media:
Setting global arguments in Settings:
=> feat: advanced mode for passing VLC commands

Screenbox/App.xaml, Screenbox/Pages/SettingsPage.xaml, Screenbox/Strings/ar-SA/Resources.resw, Screenbox/Strings/en-US/Resources.generated.cs, Screenbox/Strings/en-US/Resources.resw, Screenbox/Strings/es-ES/Resources.resw, Screenbox/Strings/ro-RO/Resources.resw, Screenbox/Strings/ru-RU/Resources.resw, Screenbox/Strings/zh-Hans/Resources.resw
Feel free to discard the comments and the footer from the about expander. Also I removed some "superfluous" FontIcon sizes.
Not 100% sure all libraries were included.
Convert the new fields to strings and please do a copywrite pass, thanks.
=> style: about section visual refresh

Screenbox.Core/Enums/ResourceName.cs, Screenbox.Core/ViewModels/PropertyViewModel.cs, Screenbox/Strings/ar-SA/Resources.resw, Screenbox/Strings/en-US/Resources.generated.cs, Screenbox/Strings/en-US/Resources.resw, Screenbox/Strings/es-ES/Resources.resw, Screenbox/Strings/ro-RO/Resources.resw, Screenbox/Strings/ru-RU/Resources.resw, Screenbox/Strings/zh-Hans/Resources.resw
Adds the [composer property](https://learn.microsoft.com/en-us/uwp/api/windows.storage.fileproperties.musicproperties.composers?view=winrt-22621) for audio files to the PropertiesView dialog. I've provisionally reused the writers string.
=> fix: add missing Composers property in PropertiesView

Screenbox/Controls/AudioTrackSubtitlePicker.xaml
=> fix: audio subtitle picker header style

Screenbox.Core/ViewModels/PlayerControlsViewModel.cs
This resolve the following crash report
> PlayerControlsViewModel.SetPlaybackSpeed (String)
System.FormatException: Input string was not in a correct format.
=> fix: set playback speed cannot handle invalid string

Screenbox.Core/Enums/ResourceName.cs, Screenbox.Core/ViewModels/MusicPageViewModel.cs, Screenbox.Core/ViewModels/VideosPageViewModel.cs, Screenbox/Strings/en-US/Resources.generated.cs, Screenbox/Strings/en-US/Resources.resw
Handle the exception gracefully and raise an error notification.
This resolves the following crash: 
> \<AddFolder\>d__16.MoveNext ()
System.Exception: The network path was typed incorrectly, does not exist, or the network provider is not currently available. Try retyping the path or contact your network administrator.
=> fix: handle exception when add folder to libraries

Screenbox.Core/ViewModels/MainPageViewModel.cs, Screenbox/Pages/MainPage.xaml
Moving focus on a suggested item would always execute the submit action. This was due to incorrect usage of `AutoSuggestBox.SuggestionChosen` event.
=> fix: search box not behaving correctly with keyboard/gamepad

.github/workflows/main.yml
WACK job did not have sufficient permissions.
=> fix: wack test fails in PRs from a fork

Screenbox/Pages/AlbumDetailsPage.xaml, Screenbox/Pages/ArtistDetailsPage.xaml
Due to weird margins on both pages, XY navigation is broken. Manually direct XY nav using `XYFocusUp` and `XYFocusDown`.
=> fix: album and artist details pages up down nav

Screenbox.Core/Playback/IMediaPlayer.cs, Screenbox.Core/Playback/PlaybackSubtitleTrackList.cs, Screenbox.Core/Playback/VlcMediaPlayer.cs, Screenbox.Core/Services/FilesService.cs, Screenbox.Core/Services/IFilesService.cs, Screenbox.Core/ViewModels/AudioTrackSubtitleViewModel.cs
Resolves #190 
Automatically load a subtitle when there is one with the same name in the same directory. The loaded subtitle is not displayed by default and is available to select in the subtitle picker.
=> feat: auto subtitle load in the same directory

Screenbox/Pages/PlayerPage.xaml.cs
Fixes #194 
When the app is file activated, the player fails to set the correct focus target since all controls are disabled by default due to the media file not yet ready. We should wait for playback and then set the correct focus.
=> fix: player focus on file activation

Screenbox/Controls/PlayerControls.xaml, Screenbox/Controls/SeekBar.xaml
Some Sliders don't have `SmallChange` set, which is used for gamepad interaction.
=> fix: Slider step size when using gamepad

Screenbox/Controls/Interactions/SettingsExpanderXYNavigationBehavior.cs, Screenbox/Pages/SettingsPage.xaml, Screenbox/Pages/SettingsPage.xaml.cs, Screenbox/Screenbox.csproj
=> fix: settings page visual and XY navigability

Screenbox.Core/Services/FilesService.cs
When exporting a video frame into a snapshot, the snapshot name is similar to `vlcsnap-2022-03-06-13h51m21s111.png`. We should avoid exposing VLC naming scheme.
Proposing new name pattern: `Screenbox_20230813_110824.png`
=> fix: snapshot name exposes VLC naming

Screenbox.Core/Screenbox.Core.csproj, Screenbox.Core/packages.lock.json, Screenbox/Screenbox.csproj, Screenbox/packages.lock.json
Downgrade LibVLCSharp due to a [subtitle rendering with a semi-transparent background issue](https://code.videolan.org/videolan/LibVLCSharp/-/issues/631).
Downgrade LibVLC due to an audio issue #230
=> fix: downgrade libvlc and libvlcsharp

Screenbox.Core/ViewModels/PlayerControlsViewModel.cs, Screenbox/Controls/PlayerControls.xaml, Screenbox/Controls/PlayerControls.xaml.cs
Allows, at a glance, to view how the playback speed is set on the context menu.
Switched to a more appropriate glyph.
=> style: change speed glyph

Screenbox.Core/Factories/MediaViewModelFactory.cs, Screenbox.Core/ViewModels/HomePageViewModel.cs, Screenbox.Core/ViewModels/MediaListViewModel.cs, Screenbox.Core/ViewModels/MediaViewModel.cs, Screenbox.Core/ViewModels/PlaylistViewModel.cs, Screenbox/Controls/PlaylistView.xaml.cs
Closes #114
This feature allows Screenbox to support IPTV.
Stream file parsing uses Lua scripts. Find a solution to reliably load Lua scripts. See related LibVLC issues
[Add lua support to LibVLC.UWP](https://code.videolan.org/videolan/libvlc-nuget/-/issues/13)
[lua: discard basedir and DIR_SEP on UWP](https://code.videolan.org/videolan/vlc/-/merge_requests/846)
Edit: Thanks to #246, this is now possible.
=> feat: add support for multi stream playlist

Screenbox.Core/ViewModels/PlayerPageViewModel.cs, Screenbox/Pages/PlayerPage.xaml
Fixes #242
Handle the Space key to toggle play/pause only when the focus is on the PlayerPage.
=> feat: override space key to toggle play pause

Screenbox/App.xaml, Screenbox/Controls/AudioTrackSubtitlePicker.xaml, Screenbox/Controls/MediaListViewItem.xaml, Screenbox/Controls/PlayerControls.xaml, Screenbox/Controls/Templates/AlbumGridViewItem.xaml, Screenbox/Controls/Templates/VideoGridViewItem.xaml, Screenbox/Pages/AlbumsPage.xaml, Screenbox/Pages/ArtistsPage.xaml, Screenbox/Pages/FolderViewPage.xaml, Screenbox/Pages/HomePage.xaml, Screenbox/Pages/MusicPage.xaml, Screenbox/Pages/PlayerPage.xaml, Screenbox/Pages/SongsPage.xaml, Screenbox/Pages/VideosPage.xaml
1. Fixes the Playback Title horizontal alignment #211
2. Changed some brushes to text specific ones
3. Reduce the probability of showing the Top NavView OverflowButton
4. Maintain the same Semantic Zoom layout on resize
5. Increased the padding of HyperlinkButton that uses CaptionTextBlockStyle to fix the vertical aligmnent at scales >100%
6. Improved the look of "Add subtitle" button visual states
=> style: minor ui changes

Screenbox.Core/ViewModels/MediaListViewModel.cs, Screenbox/Screenbox.csproj, Screenbox/packages.lock.json
Fix an issue where playlist files are not parsed on load. VLC would skip parsing the file because `winrt` protocol is an unknown type. Fixed in https://github.com/huynhsontung/libvlc-nuget/pull/11
=> fix: multi-stream playlist parse

Screenbox.Core/Playback/VlcMediaPlayer.cs, Screenbox.Core/ViewModels/MediaListViewModel.cs
Simplify item processing logic across `VlcMediaPlayer` and `MediaListViewModel`. Consolidate all item parsing on enqueue in `MediaListViewModel`.
Fixes #257
=> fix: improve item processing on playlist enqueue

Screenbox/Screenbox.csproj, Screenbox/packages.lock.json
HDR contents appear blown out on an SDR screen. Fixed in LibVLC: https://github.com/huynhsontung/libvlc-nuget/pull/12
=> fix: incorrect color space when rendering HDR content on SDR screen

Screenbox.Core/Factories/MediaViewModelFactory.cs, Screenbox.Core/Screenbox.Core.csproj, Screenbox.Core/Services/SystemMediaTransportControlsService.cs, Screenbox.Core/ViewModels/AudioTrackSubtitleViewModel.cs, Screenbox.Core/ViewModels/FileMediaViewModel.cs, Screenbox.Core/ViewModels/HomePageViewModel.cs, Screenbox.Core/ViewModels/MediaListViewModel.cs, Screenbox.Core/ViewModels/MediaViewModel.cs, Screenbox.Core/ViewModels/PlayQueuePageViewModel.cs, Screenbox.Core/ViewModels/PlayerPageViewModel.cs, Screenbox.Core/ViewModels/PropertyViewModel.cs, Screenbox.Core/ViewModels/UriMediaViewModel.cs
Split `MediaViewModel` into `FileMediaViewModel` and `UriMediaViewModel`. Both new classes are derived from `MediaViewModel`.
=> refactor: split one common media vm into subclasses

Screenbox.Core/ViewModels/FileMediaViewModel.cs, Screenbox.Core/ViewModels/MediaViewModel.cs, Screenbox.Core/ViewModels/UriMediaViewModel.cs
LibraryService cannot reliably create and restore cache due to inconsistent `Location` values between `UriMediaViewModel` and `FileMediaViewModel`.
=> fix: inconsistent ID between Uri media and file media

Screenbox.Core/Services/LibraryService.cs, Screenbox.Core/ViewModels/MediaListViewModel.cs, Screenbox.Core/ViewModels/SettingsPageViewModel.cs, Screenbox.Core/ViewModels/UriMediaViewModel.cs, Screenbox.Core/ViewModels/VideosPageViewModel.cs, Screenbox/App.xaml.cs, Screenbox/Controls/OpenUrlDialog.xaml.cs, Screenbox/Pages/AlbumDetailsPage.xaml
The following changes are included:
- catch task canceled exception when parsing playlist
- handle IsRightToLeftLanguage exception
- enforce try create Uri in open url dialog
- handle UnauthorizedAccessException when getting file from path
- ignore media pool empty exception
- fix binding error for album details page when there is no related item
- handle unauthorized exceptions on manual library refresh
- delay VideosPage breadcrumbs population until navigation
=> fix: handle various exceptions

Screenbox.Core/Messages/UpdateStatusMessage.cs, Screenbox.Core/Messages/UpdateVolumeStatusMessage.cs, Screenbox.Core/ViewModels/MainPageViewModel.cs, Screenbox.Core/ViewModels/PlayerElementViewModel.cs, Screenbox.Core/ViewModels/PlayerPageViewModel.cs
Fixes #266
Persistent status message forces the caller to manually dismiss the status message. We lose timeout ability this way. Just remove it and force every caller to follow the same timeout.
=> fix: status message disappears too quickly when using touch gestures

Screenbox/Pages/SettingsPage.xaml, Screenbox/Strings/en-US/Resources.generated.cs, Screenbox/Strings/en-US/Resources.resw
Don't expand cards by default.
Privacy, license, and source should be hidden by default. Other links should be outside for the expander for more visibility
=> chore(ui): settings page minor adjustments

Screenbox/Controls/Interactions/AlternatingListViewBehavior.cs
Item containers may be cached if the list is previously loaded and `ContainerContentChanging` event is not triggered. Always refresh layout container on behavior attached.
https://github.com/huynhsontung/Screenbox/assets/31434093/84f443b7-6afb-43b2-a18d-5d7249ae5245
=> fix: alternate layout not updating on previously loaded list views

.github/workflows/main.yml, Screenbox/Screenbox.csproj
Speed up build CI by building for different platforms in parallel
=> ci: dont bundle platforms together

Screenbox/Controls/MediaListViewItem.xaml, Screenbox/Controls/Styles/Subtle_themeresources.xaml, Screenbox/Pages/PlayerPage.xaml, Screenbox/Pages/SettingsPage.xaml
- Revert the beginning of the PlayerPage gradients to a pure black shade
- Brings back the 'Back' button animation on PlayerPage
- Reworked the padding on a couple of buttons to prevent glyph cut-off at some scales
- (HighContrast) Use the same foreground brush on the MediaListView buttons
=> fix(ui): minor UI fixes

.github/workflows/main.yml, Screenbox/Screenbox.csproj, Screenbox/packages.lock.json
Fixed an issue caused by native DLLs used by LibVLC are included as content files by the libvlc nuget package.
Fixed at the nuget level: https://github.com/huynhsontung/libvlc-nuget/pull/15
Permanently fixes https://github.com/huynhsontung/Screenbox/issues/123
=> fix: resources inconsistent between target platforms

Screenbox.Core/Helpers/FilesHelpers.cs, Screenbox.Core/Models/MediaInfo.cs, Screenbox.Core/Services/FilesService.cs, Screenbox.Core/ViewModels/MediaViewModel.cs, Screenbox.Core/ViewModels/PlayerPageViewModel.cs
Try best to guess the media type as early as possible. Relying on async methods can fail and leave media with unknown media type.
=> fix: wrong media type can be set on file load

Screenbox/Screenbox.csproj, Screenbox/packages.lock.json
Fixes #345 
LibVLC built with Mingw-w64 version higher than v9.0.0 fails to find Chromecast targets. Fixed in https://github.com/huynhsontung/libvlc-nuget/pull/18
=> fix: chromecast can't finding cast targets

Screenbox.Core/Services/INavigationService.cs, Screenbox.Core/Services/NavigationService.cs, Screenbox/Pages/PlayerPage.xaml.cs
Navigation from the playlist flyout when the player is visible does not work as expected. The app gets stuck in a non-recoverable UI state.
Fixes #331
=> fix: navigation from playlist flyout

Screenbox/Controls/CommonGridViewItem.xaml, Screenbox/Controls/MediaListViewItem.xaml, Screenbox/Pages/AlbumDetailsPage.xaml, Screenbox/Pages/ArtistDetailsPage.xaml, Screenbox/Pages/FolderListViewPage.xaml, Screenbox/Pages/FolderViewPage.xaml, Screenbox/Pages/PlayerPage.xaml, Screenbox/Pages/Search/AlbumSearchResultPage.xaml, Screenbox/Pages/Search/ArtistSearchResultPage.xaml, Screenbox/Pages/Search/SearchResultPage.xaml, Screenbox/Pages/Search/SongSearchResultPage.xaml, Screenbox/Pages/Search/VideoSearchResultPage.xaml
=> chore: add tooltips to overflowed textblocks

Screenbox.Core/Helpers/VlcMediaExtensions.cs, Screenbox.Core/Screenbox.Core.csproj, Screenbox.Core/ViewModels/MediaListViewModel.cs, Screenbox.Core/ViewModels/MediaViewModel.cs, Screenbox/Controls/OpenUrlDialog.xaml.cs
- Handle playlist parse timeout. Closes #364 
- Fix URL media is not parsed when adding directly to the play queue without playing first.
- Enforce all media URLs to be absolute URLs.
- Remove wait time when opening a URL. Provide instant UI feedback while media is being parsed in the background.
=> fix: better handle sub media parsing

Screenbox.Core/Playback/VlcMediaPlayer.cs, Screenbox.Core/Services/LibVlcService.cs, Screenbox.Core/ViewModels/MediaViewModel.cs, Screenbox/Screenbox.csproj, Screenbox/packages.lock.json
This LibVLC version adds support for opening StorageFile using SharedStorageAccessManager tokens. Too bad they are too restrictive compared to FutureAccessList.
The plugin source code is located in https://github.com/huynhsontung/libvlc-winrt-plugins
=> chore: bump LibVLC version

Screenbox.Core/Factories/MediaViewModelFactory.cs, Screenbox.Core/ViewModels/AudioTrackSubtitleViewModel.cs, Screenbox.Core/ViewModels/MediaListViewModel.cs, Screenbox.Core/ViewModels/MediaViewModel.cs, Screenbox.Core/ViewModels/PlayerPageViewModel.cs
Use Lazy<T> to initialize PlaybackItem instead of getter-based initialization.
=> feat: lazily initialize PlaybackItem

Screenbox.Core/Services/LibraryService.cs
`Windows.Storage.StorageLibraryChangeReader.GetLastChangeId()` is not available in older versions of Windows. Fixed bug introduced in #373
=> fix: library cache using a method that is unavailable in older versions of Windows

Screenbox.Core/Services/LibraryService.cs, Screenbox.Core/ViewModels/FolderViewPageViewModel.cs, Screenbox.Core/ViewModels/SettingsPageViewModel.cs, Screenbox.Core/ViewModels/VideosPageViewModel.cs
Check and request access to library and removable device folders before accessing them.
=> fix: handle permission request for removable devices on Xbox

Screenbox.Core/Services/ISettingsService.cs, Screenbox.Core/Services/SettingsService.cs, Screenbox.Core/ViewModels/SettingsPageViewModel.cs, Screenbox/Package.appxmanifest, Screenbox/Pages/SettingsPage.xaml, Screenbox/Program.cs, Screenbox/Screenbox.csproj, Screenbox/Strings/en-US/Resources.generated.cs, Screenbox/Strings/en-US/Resources.resw
=> feat: add multi-instance support

Screenbox/Pages/SettingsPage.xaml
Use checkbox when the change is not instantly reflected and toggle switch otherwise
=> chore: revisit toggle switch or checkbox usage on settings page

Screenbox.Core/Services/ISettingsService.cs, Screenbox.Core/Services/SettingsService.cs, Screenbox.Core/ViewModels/PlayerPageViewModel.cs, Screenbox.Core/ViewModels/SettingsPageViewModel.cs, Screenbox/Pages/SettingsPage.xaml, Screenbox/Strings/en-US/Resources.generated.cs, Screenbox/Strings/en-US/Resources.resw, Screenbox/Strings/zh-Hans/Resources.resw
I often use screenshot software (e.g. pixpin, snipaste) to take a screenshot of the video directly and copy it to the clipboard, which is very easy to share. Therefore I seldom need to save the frame as a file. However, the controls keep displaying when paused, which is not convenient for taking screenshots directly. So I added a setting to control whether the controls will be displayed when paused. The controls will disappear after a while when paused. When pause with spacebar, it will not show the controls.
=> feat: Add option to not display controls on pause

Screenbox.Core/ViewModels/SeekBarViewModel.cs, Screenbox/Controls/SeekBar.xaml, Screenbox/Controls/SeekBar.xaml.cs
=> feat: pointer wheel scroll on seekbar to seek

Screenbox.Core/ViewModels/LivelyWallpaperPlayerViewModel.cs, Screenbox.Core/ViewModels/LivelyWallpaperSelectorViewModel.cs, Screenbox/Pages/PlayerPage.xaml, Screenbox/Pages/PlayerPage.xaml.cs
Fix an issue where a lively visual is always selected by default and the lively player is always loaded.
=> fix: Lively visual is always selected

Screenbox.Core/Screenbox.Core.csproj, Screenbox.Core/packages.lock.json, Screenbox/Controls/PlayerElement.xaml, Screenbox/Controls/PlayerElement.xaml.cs, Screenbox/packages.lock.json
Temporary fix for #427. Revert LibVlcSharp to 3.7.0.
=> fix: temporary solution for the audio stuttering issue

Screenbox.Core/Helpers/StreamAbstraction.cs, Screenbox.Core/Screenbox.Core.csproj, Screenbox.Core/Services/FilesService.cs, Screenbox.Core/Services/IFilesService.cs, Screenbox.Core/ViewModels/AlbumDetailsPageViewModel.cs, Screenbox.Core/ViewModels/AlbumViewModel.cs, Screenbox.Core/ViewModels/AlbumsPageViewModel.cs, Screenbox.Core/ViewModels/ArtistDetailsPageViewModel.cs, Screenbox.Core/ViewModels/HomePageViewModel.cs, Screenbox.Core/ViewModels/MediaListViewModel.cs, Screenbox.Core/ViewModels/MediaViewModel.cs, Screenbox.Core/ViewModels/PlayerPageViewModel.cs, Screenbox.Core/packages.lock.json, Screenbox/Controls/Interactions/ThumbnailGridViewBehavior.cs, Screenbox/Controls/LivelyWebWallpaperPlayer.xaml.cs, Screenbox/Pages/AlbumDetailsPage.xaml.cs, Screenbox/packages.lock.json
Use TaglibSharp to extract high-quality thumbnails from (mostly) audio files. There will be more use for TablibSharp down the line.
=> feat: use TaglibSharp for album art extraction

Screenbox/Pages/MainPage.xaml, Screenbox/Pages/MusicPage.xaml, Screenbox/Pages/VideosPage.xaml, Screenbox/Strings/en-US/Resources.generated.cs, Screenbox/Strings/en-US/Resources.resw
Fixes #457 
The translation of "Music" in some languages doesn't convey the music library in context. Create a dedicated string to accommodate for these differences
=> l10n: create dedicated strings for music and video libraries

Screenbox.Core/ViewModels/PlaylistViewModel.cs, Screenbox/Controls/MediaListViewItem.xaml, Screenbox/Controls/PlaylistView.xaml, Screenbox/Controls/PlaylistView.xaml.cs
Remove the `MultipleSingleSelected` visual state. Promote "Move up" and "Move down" buttons to primary commands.
=> style: simplify PlaylistView UI logic

Screenbox/Controls/CommonGridViewItem.xaml, Screenbox/Controls/LivelyWallpaperSelector.xaml, Screenbox/Pages/AlbumDetailsPage.xaml, Screenbox/Pages/ArtistDetailsPage.xaml, Screenbox/Pages/PlayerPage.xaml
Resolves #429 regression on some images. `ImageBrush`, unlike the [Image](https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.image?view=winrt-26100#flowdirection-for-image) control, doesn't enforce a `LeftToRight` direction.
=> fix: correct ImageBrush orientation for RTL languages

Screenbox/App.xaml, Screenbox/Controls/CommonGridViewItem.xaml, Screenbox/Controls/PlaylistView.xaml, Screenbox/Pages/AlbumDetailsPage.xaml, Screenbox/Pages/AlbumsPage.xaml, Screenbox/Pages/ArtistDetailsPage.xaml, Screenbox/Pages/ArtistsPage.xaml, Screenbox/Pages/HomePage.xaml, Screenbox/Pages/MainPage.xaml, Screenbox/Pages/MusicPage.xaml, Screenbox/Pages/PlayQueuePage.xaml, Screenbox/Pages/SettingsPage.xaml, Screenbox/Pages/SongsPage.xaml, Screenbox/Pages/VideosPage.xaml, Screenbox/Styles/Button.xaml
Based on the design pattern outlined in the Figma WinUI document, the icon should be vertically centered within buttons.
The margin also makes sure that buttons maintain a consistent height in the icon only layout, especially important for those that hide the text content in the minimal visual state.
=> style: adjust icon vertical alignment in buttons

Screenbox.Core/ViewModels/MediaViewModel.cs
TagLib read is not critical. Fix various crashes caused by exceptions thrown by TagLib
=> fix: pass all TagLib exceptions

Screenbox/App.xaml, Screenbox/Pages/AlbumsPage.xaml, Screenbox/Pages/ArtistsPage.xaml, Screenbox/Pages/HomePage.xaml, Screenbox/Pages/MainPage.xaml, Screenbox/Pages/MainPage.xaml.cs, Screenbox/Pages/NetworkPage.xaml, Screenbox/Pages/PlayerPage.xaml, Screenbox/Pages/SongsPage.xaml
- Adjust custom accent brush to align with WinUI
- Fix `AppTitleBar` title inactive brush on theme switching
- Fix, and adjust, `PlayerPage` `Header` and `PlayerControls` background for the light theme
- Remove some `XamlUICommand`
- Fix "squashed" `ShuffleAndPlay` button in the `ArtistsPage` minimal visual state
- Fix potential overlap between `BreadcrumbBar` and `NoNetworkDrivePanel` on `NetworkPage`
- Add `ScrollViewer.Is*ScrollChainingEnabled` to `SemanticZoom` control according to the [documentation](https://learn.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.semanticzoom?view=winrt-26100)
=> style: minor UI fixes

.github/workflows/main.yml
~~Fix wack check failing after merging #479~~
Update: A new GitHub Actions Windows image release broke wack test. https://github.com/actions/runner-images/releases/tag/win22%2F20241113.3
Attempt to fix this issue by using an older Windows runner.
=> fix(ci): wack test failing

Screenbox.Core/Common/ServiceHelpers.cs, Screenbox.Core/ViewModels/HomePageViewModel.cs, Screenbox.Core/ViewModels/MainPageViewModel.cs, Screenbox/Pages/MainPage.xaml.cs
Media load speed is pretty fast and stable now. There is no reason to cache the MRU result in the home page view model. Keeping the home page view model as a singleton can sometimes encounter race conditions.
Since home page is no longer a singleton, we can't rely on the home page load to trigger library fetching. Move that logic to main page.
=> chore: make home page view model transient

Screenbox.Core/Helpers/LivelyWallpaperUtil.cs, Screenbox.Core/Helpers/WebView2Util.cs, Screenbox.Core/Services/LivelyWallpaperService.cs, Screenbox.Core/ViewModels/LivelyWallpaperPlayerViewModel.cs, Screenbox/Controls/LivelyWallpaperSelector.xaml, Screenbox/Controls/LivelyWebWallpaperPlayer.xaml.cs, Screenbox/Pages/PlayerPage.xaml, Screenbox/Screenbox.csproj, Screenbox/Strings/en-US/Resources.generated.cs, Screenbox/Strings/en-US/Resources.resw
- Normalized hostname argument for `WebView2.NavigateToLocalPath()` and handle exceptions if occurs.
- Simplified Lively wallpaper installs using less async methods and reusing `ZipArchive` references.
- Propagate Lively related exceptions to app notifications instead of passing them.
- Move all JavaScript integration code and track change logic in the `LivelyWallpaperPlayerViewModel`.
=> fix: various lively wallpaper issues

Screenbox.Core/ViewModels/MediaListViewModel.cs, Screenbox.Core/ViewModels/MediaViewModel.cs, Screenbox/Controls/MediaListViewItem.xaml
Track availability in the `MediaViewModel` and add an unavailable state to the `MediaListViewItem`. This will be useful for managing playlists where not all files can be reached using the file path.
=> feat: track media availability

Screenbox.Core/Services/FilesService.cs, Screenbox.Core/Services/ISettingsService.cs, Screenbox.Core/Services/SettingsService.cs, Screenbox.Core/ViewModels/MediaListViewModel.cs, Screenbox.Core/ViewModels/SettingsPageViewModel.cs, Screenbox/Pages/SettingsPage.xaml, Screenbox/Strings/en-US/Resources.generated.cs, Screenbox/Strings/en-US/Resources.resw
This PR implements
- Perform recursive folder search when dropping a mix of files and folders into the app. Closes #482 
- Add an option to automatically add all media files in a folder into the play queue upon opening a single file. Close #497 #441
=> feat: improve folder support

Screenbox/Package.appxmanifest
Replaces the `.mp4` and `.3gpp` file type logos with the video icon instead of the media icon.
=> chore: update the logo for mp4 and 3gpp file types

Screenbox.Core/Services/IWindowService.cs, Screenbox.Core/Services/WindowService.cs, Screenbox.Core/ViewModels/PlayerPageViewModel.cs, Screenbox/Pages/PlayerPage.xaml
This pull request includes several changes to the `Screenbox.Core` services and view models to enhance the window resizing functionality and improve keyboard shortcuts for resizing. 
- Change the resize preset number 3 to use a scalar value of 1.5 instead of 2. Scaling to 2 often results in excessive enlargement for 1080p videos displayed on a 2K or 4K screen. Using preset number 4 can often achieve a similar outcome.
- Implement window resizing by 10% step using Ctrl + Plus and Ctrl + Minus.
https://github.com/user-attachments/assets/6317ceae-ff57-4c63-93f2-309ad8ba4702
=> feat: window resize steps using Ctrl + Plus and Ctrl + Minus

Screenbox.Core/Common/ServiceHelpers.cs, Screenbox.Core/Helpers/LanguageHelper.cs, Screenbox.Core/Helpers/VlcMediaExtensions.cs, Screenbox.Core/Playback/MediaTrack.cs, Screenbox.Core/Screenbox.Core.csproj, Screenbox.Core/Services/ISettingsService.cs, Screenbox.Core/Services/SettingsService.cs, Screenbox.Core/ViewModels/AudioTrackSubtitleViewModel.cs, Screenbox.Core/ViewModels/CompositeTrackPickerViewModel.cs, Screenbox/Controls/CompositeTrackPicker.xaml, Screenbox/Controls/CompositeTrackPicker.xaml.cs, Screenbox/Controls/PlayerControls.xaml, Screenbox/Screenbox.csproj
When users select a subtitle, they will likely want the same subtitle **language** for the next media, similar to how YouTube operates. Since there is no standard method to detect the language of a subtitle track, we attempt to retain and compare both the language tag and the language label of the track. If both methods fail, we will select based on the preferred system language.
The logic is as follows:
- When the user opens the subtitle track picker and selects a subtitle, the app tries to guess what language the subtitle track is and remembers that information.
- When opening another media file, if the persistent value is not empty
- Select the first subtitle track if there is only one.
- Try to find the first subtitle track in the same language if there is more than one.
- Reset the …
=> feat: improve subtitle picking logic - persist subtitle language selection

Screenbox.Core/Helpers/LastPositionTracker.cs, Screenbox.Core/ViewModels/AlbumDetailsPageViewModel.cs, Screenbox.Core/ViewModels/ArtistDetailsPageViewModel.cs, Screenbox.Core/ViewModels/ArtistViewModel.cs, Screenbox.Core/ViewModels/HomePageViewModel.cs, Screenbox.Core/ViewModels/LivelyWallpaperPlayerViewModel.cs, Screenbox.Core/ViewModels/MediaViewModel.cs, Screenbox/Pages/AlbumDetailsPage.xaml, Screenbox/Pages/AlbumDetailsPage.xaml.cs, Screenbox/Pages/ArtistDetailsPage.xaml, Screenbox/Pages/ArtistDetailsPage.xaml.cs
This pull request includes several changes to improve null safety and handle potential exceptions in the `Screenbox.Core` project.
- Ignore all MRU related exceptions
- Fix last position tracker uses the main storage list directly in an async save function. The list can change and cause enumeration exceptions.
- Better null handling for Artist and Album details pages
- Handle exception when trying to convert `Uri` into `StorageFile`
- Check for CoreWebView2 is initialized before accessing to avoid null exception
=> fix: various crashing exceptions

Screenbox.Core/Services/LibVlcService.cs, Screenbox.Core/ViewModels/MediaViewModel.cs
Since SharedStorageAccessManager does not work with network files. We can use the file path directly in those cases instead.
=> feat: use SharedStorageAccessManager as a fallback for FutureAccessList

Screenbox.Core/ViewModels/MediaListViewModel.cs
Missing null check, try to play the media before the player is initialized. Bug introduced in #517
=> fix: media not playing when launch from file

Screenbox/Controls/Interactions/SettingsExpanderXYNavigationBehavior.cs, Screenbox/Pages/SettingsPage.xaml
- Removes the SettingsCard merged resource dictionary
- Adds the RTL header icon for EnqueueAllFilesInFolder SettingsCard
- Simplifies the SettingsExpander XY focus behavior, eliminating the need for a control to be set as a target
=> chore: minor settings page improvements

.github/workflows/main.yml, Screenbox.Core/ViewModels/CastControlViewModel.cs, Screenbox.Core/ViewModels/MediaListViewModel.cs, Screenbox/App.xaml.cs, Screenbox/Pages/MainPage.xaml.cs
Now that we have a self-hosted Sentry, we can go ham with the settings.
Use Sentry CLI to create and associate symbols and commits to releases.
Replace all AppCenter usages for analytics and error reporting and replace them with Sentry's ones. AppCenter is still active but is considered deprecated and will be removed in March 2025.
=> feat: enrich Sentry error reporting

Screenbox/App.xaml, Screenbox/Controls/CompositeTrackPicker.xaml, Screenbox/Controls/NotificationView.xaml.cs, Screenbox/Controls/PlaylistView.xaml, Screenbox/Pages/AlbumDetailsPage.xaml, Screenbox/Pages/ArtistDetailsPage.xaml, Screenbox/Pages/HomePage.xaml.cs, Screenbox/Pages/MainPage.xaml, Screenbox/Pages/MainPage.xaml.cs, Screenbox/Pages/PlayerPage.xaml, Screenbox/Pages/PlayerPage.xaml.cs, Screenbox/Pages/SettingsPage.xaml, Screenbox/Pages/SettingsPage.xaml.cs, Screenbox/Styles/Button.xaml, Screenbox/Styles/ItemContainer.xaml
- Fixes `CompositeTrackPicker` add subtitle button foreground brush for high contrast
- Fixes media group header border brush on light mode
- Disables the back button when the window is not active, according to the design documentation
- Combines and moves `ThemeShadow` resources to the app resources
- Replaces the drag UI caption verb from 'Open' to 'Play'
=> style: minor UI fixes and optimizations

Screenbox/Pages/PlayerPage.xaml, Screenbox/Pages/PlayerPage.xaml.cs
There is a bug that makes WebView always loaded by default. This is because of the transition storyboard animation, as mentioned in the [x:Load attribute](https://learn.microsoft.com/en-us/windows/uwp/xaml-platform/x-load-attribute#loading-elements) docs.
=> fix: unexpected lively player load due to Storyboard animation

Screenbox.Core/Helpers/EnumExtensions.cs, Screenbox.Core/Screenbox.Core.csproj, Screenbox.Core/ViewModels/CommonViewModel.cs, Screenbox.Core/ViewModels/PlayerPageViewModel.cs, Screenbox.Core/ViewModels/SettingsPageViewModel.cs, Screenbox/App.xaml.cs, Screenbox/Pages/PlayerPage.xaml, Screenbox/Pages/PlayerPage.xaml.cs, Screenbox/Pages/SettingsPage.xaml, Screenbox/Strings/en-US/Resources.generated.cs, Screenbox/Strings/en-US/Resources.resw
Closes #539 #361
Move the theme change setting to its own category on the settings page. Changing the theme on the settings page takes effect immediately without requiring an app restart.
I also fixed an issue with the `PlayerPage` theme propagation, where the page would not respect the theme requested by the parent.
https://github.com/user-attachments/assets/3eb10a55-53d9-42bc-b57d-4d08db4bb152
=> feat: improve app theme change

.editorconfig
Some minor updates and, adds the `dotnet_sort_system_directives_first = true` and `csharp_indent_case_contents_when_block = false` configs.
=> chore: minor editorconfig update

Screenbox/Pages/MainPage.xaml, Screenbox/Strings/en-US/Resources.generated.cs, Screenbox/Strings/en-US/Resources.resw
Changes the design of the critical error panel to resemble the BSOD.
Edit: Mockup added
=> style: critical error panel redesign

Screenbox.Core/Common/ServiceHelpers.cs, Screenbox.Core/Helpers/LastPositionTracker.cs, Screenbox.Core/Services/ISettingsService.cs, Screenbox.Core/Services/SettingsService.cs, Screenbox.Core/ViewModels/PlayerPageViewModel.cs, Screenbox.Core/ViewModels/SeekBarViewModel.cs, Screenbox.Core/ViewModels/SettingsPageViewModel.cs, Screenbox/Pages/SettingsPage.xaml, Screenbox/Strings/en-US/Resources.generated.cs, Screenbox/Strings/en-US/Resources.resw
Closes #495
Add the ability to always resume from the last position when opening a previously played file. This PR also refactor `LastPositionTracker` to participate in dependency injection. The instance is now hosted by the `SeekBarViewModel` instead of the `PlayerPageViewModel`.
=> feat: add option to always resume from the last position

Screenbox.Core/Messages/DragDropMessage.cs, Screenbox.Core/Screenbox.Core.csproj, Screenbox.Core/ViewModels/HomePageViewModel.cs, Screenbox.Core/ViewModels/MainPageViewModel.cs, Screenbox.Core/ViewModels/PlayerPageViewModel.cs, Screenbox.Core/ViewModels/PlaylistViewModel.cs, Screenbox/Controls/PlaylistView.xaml.cs, Screenbox/Pages/HomePage.xaml, Screenbox/Pages/HomePage.xaml.cs, Screenbox/Pages/MainPage.xaml, Screenbox/Pages/MainPage.xaml.cs, Screenbox/Pages/PlayerPage.xaml, Screenbox/Pages/PlayerPage.xaml.cs
Users can only drag and drop over the HomePage or the PlayerPage to play media. This PR allows users to drag and drop to play files almost anywhere on the app.
=> feat: drag and drop anywhere to play

Screenbox.Core/Screenbox.Core.csproj, Screenbox.Core/packages.lock.json, Screenbox/App.xaml.cs, Screenbox/Screenbox.csproj, Screenbox/packages.lock.json
Use `CoreApplication.UnhandledErrorDetected` instead of `Application.UnhandledException` to retain more information in the Exception.
Modifying Sentry SDK configuration to use an updated release version format and tag device family information. This change unifies the release versioning for both PC and Xbox versions.
=> fix: Sentry error reporting for unhandled exceptions

Screenbox/App.xaml, Screenbox/Converters/ThicknessFilterConverter.cs
Enhancements to `ThicknessFilterConverter`:
* Updated the `ThicknessFilterConverter` class to be sealed and inherit from `DependencyObject`. Added detailed XML documentation and an example to illustrate usage.
* Modified the `ThicknessFilterKind` enum to support bitwise combinations, allowing more flexible filtering. 
* Renamed the `ExcludeConvert` method to `ExtractThickness` and updated its logic to handle bitwise filter combinations.
=> chore: refactor and add comments to thickness converter

Screenbox/Controls/ChapterProgressBar.xaml.cs, Screenbox/Screenbox.csproj
Potentially fixes #591 
Handle cases where there are gaps between chapters which leads to the chapter progress bar length does not match the seek bar length.
=> fix: handle total chapters duration different from media duration

Screenbox/App.xaml, Screenbox/Converters/ThicknessFilterConverter.cs, Screenbox/Styles/Button.xaml
Refactors the converter for improved usability (specially for C#) and simplicity.
- Moves the enum outside the class for improved usability
- Renames the enum to follow the naming [guidelines](https://learn.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-classes-structs-and-interfaces#naming-enumerations) by using the plural form
- Renames the `ExtractThickness` method to `Convert` for improved usability
- Simplifies the filtering logic by replacing the switch statement with the `HasFlag` method
- Small adjustments to the converter `XAML` resource names
- Improves and adds some comments remarks
=> chore: minor improvements to the ThicknessFilterConverter

Screenbox.Core/ViewModels/CommonViewModel.cs, Screenbox/Controls/PlaylistView.xaml, Screenbox/Controls/PlaylistView.xaml.cs
Replaces the `SelectionCheckBox` click event with a re-usable command.
=> chore: refactor PlaylistView selection handling

Screenbox/Controls/NotificationView.xaml.cs, Screenbox/Pages/MainPage.xaml, Screenbox/Pages/SettingsPage.xaml, Screenbox/Pages/SettingsPage.xaml.cs
Fixes #654. InfoBar doesn't play nice with ThemeShadow, so I removed it entirely. Alternatively, we could apply the ThemeShadow property only when `InfoBar.IsOpen="True"`.
Before|After
-|-
=> fix: InfoBar shadow artifact

Screenbox/Controls/PlaylistView.xaml, Screenbox/Extensions/ApplicationViewExtensions.cs, Screenbox/Extensions/CommandBarExtensions.cs, Screenbox/Extensions/ListViewExtensions.cs, Screenbox/Extensions/SplitButtonExtensions.cs, Screenbox/Pages/AlbumDetailsPage.xaml, Screenbox/Pages/ArtistDetailsPage.xaml, Screenbox/Pages/FolderListViewPage.xaml, Screenbox/Pages/HomePage.xaml, Screenbox/Pages/PlayQueuePage.xaml, Screenbox/Pages/PlayerPage.xaml, Screenbox/Pages/Search/AlbumSearchResultPage.xaml, Screenbox/Pages/Search/ArtistSearchResultPage.xaml, Screenbox/Pages/Search/SearchResultPage.xaml, Screenbox/Pages/Search/SongSearchResultPage.xaml, Screenbox/Pages/Search/VideoSearchResultPage.xaml, Screenbox/Pages/SongsPage.xaml, Screenbox/Screenbox.csproj, Screenbox/Styles/ItemContainer.xaml
This PR introduces a shared ListView style to enforce (and simplify) consistent UI across multiple XAML files. Certain properties remain in the container style and haven't been migrated yet, as they're still pending performance evaluation.
- Moves the extension files from the `Controls` directory to the project root
- Updates the `ApplicationViewExtensions` header to include the appropriate copyright notice
- Adds and improves the `ListViewExtensions` attached properties
- Adds a `MediaListViewStyle` to standardize the style
- Fixes the visual feedback on the search pages `ListView`
=> style: add ListView style and improve the extension

Screenbox.Core/ViewModels/VolumeViewModel.cs, Screenbox/Controls/PlayerControls.xaml, Screenbox/Controls/VolumeControl.xaml, Screenbox/Controls/VolumeControl.xaml.cs, Screenbox/Converters/GlyphConverter.cs, Screenbox/Helpers/GlyphConvert.cs, Screenbox/Pages/PlayerPage.xaml, Screenbox/Pages/SettingsPage.xaml, Screenbox/Screenbox.csproj
- Renamed and moved `GlyphConvert`
- Moved volume glyph from `VolumeViewModel` to `GlyphConverter`
- Moved volume `OnPointerWheelChanged` from `VolumeViewModel` to the control view
=> chore: refactor volume control glyph and pointer wheel event

Screenbox.Core/ViewModels/PlayerControlsViewModel.cs
This pull request updates the file naming logic when saving snapshots in the media player controls. The main change corrects the timestamp format used in the filename to ensure dates are saved in the proper format.
* Snapshot saving logic:
* In `PlayerControlsViewModel.cs`, the file naming pattern in `SaveSnapshotInternalAsync` now uses `DateTimeOffset.Now:yyyyMMdd_HHmmss` instead of `DateTime.Now:yyyymmdd_HHmmss`, fixing the date format and ensuring the filename reflects the correct date and time.
=> fix: date formatting used when saving snapshot files

Screenbox/Converters/ResourceNameToResourceStringConverter.cs
Updates the `ResourceNameToResourceStringConverter` with .NET Foundation license header and improves nullability handling.
=> chore: add attribution to ResourceNameToResourceStringConverter
